name: FloatingPlayerStats
main: FloatingPlayerStats\MainClass
version: 0.1
api: [2.0.0]

author: seetch
description: PlayerStats in FloatingText!
website: https://github.com/seetch/FloatingPlayerStats
